### ISSUE TITLE
More specific time

### ISSUE THREAD

**Issue by n9010** [ckuma/scplay#1]
Hi, the way the time played is displayed is a bit confusing,
Congrats, you've played 8 days, 17:31:15
What does that mean? 8 days and 17h? (so 209h?).

**Comment by ckuma** [comment]
Honestly I just let the datetime library figure it out when writing the script  
Specifially it's [datetime's "timedelta" objects ](https://docs.python.org/3/library/datetime.html#timedelta-objects) that print things this way, and since dates/times are very much a matter of opinion (24h format? total hours or total days + extra? what about microseconds? etc), I didn't go a particular way with this other than the default handling of the library.  

Frankly this was a quick foray into Python scripting, and the resulting exe with GUI is also really big for what I was hoping to achieve with such a small script, but alas it's the way Python goes.  
If I rewrote this I'd probably pick a language more likely to result in a near GUI and filesize, but if you want to either fork it (to make needed changes) or create a PR for any format you deem more friendly (on this repo), the code is completely yours too :)

**Comment by n9010** [comment]
Ok, Thanks. I'll see what i can do.
